config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/about/isabelle', to: 'static_pages#about_isabelle'
  get '/about/binome', to: 'static_pages#about_binome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def about_isabelle
  end

  def about_binome
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
  <nav>
    <ul>
      <li><%= link_to "Accueil",   root_path %></li>
      <li><%= link_to "A propos", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://thehackingproject.org/">| The Hacking Project</a></li>
    </ul>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JeMePresente</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/yegor256/tacit@gh-pages/tacit-0.8.1.min.css"/>

  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>A propos</h1>
<p>Comment a été réalisé cette merveille ? Question hautement pertinente dont la réponse est pourtant simple : en <em>Ruby on Rails</em> ! Et oui c'est ça le secret de sa beauté !</p>
<p>Si vous voulez en savoir plus sur les personnes ayant réalisé ce site cliquez simplement sur leur nom :</p>
<ul>
  <li><%= link_to "Isabelle", about_isabelle_path %></li>
  <li><%= link_to "Binôme", about_binome_path %></li>
</ul>

app/views/static_pages/about_binome.html.erb
<h1>A propos du binôme</h1>
<p>Le binôme est normalement quelqu'un avec qui on travaille, mais dans mon cas c'est plus proche de ce que certains appellent un ami immaginaire...</p>

app/views/static_pages/about_isabelle.html.erb
<h1>A propos d'Isabelle</h1>
<p>Vous vous demandez qui je suis et comment j'ai pu réaliser cette merveille ? Consultez <a href="https://www.linkedin.com/in/bonnetisabelle/">mon profil LinkedIn</a> et vous comprendrez...</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>Si vous avez des questions, vous pouvez les poser à Charles Dacquay en l'appelant au : 06 95 46 60 80.</p>

app/views/static_pages/home.html.erb
<h1>Bienvenue sur le plus beau site de la Terre</h1>
<p>Attention les yeux, ceci est très clairement le plus beau site que vous n'avez jamais vu...</p>